### PR TITLE
Add some methods for:

### PR DESCRIPTION
**Pull request by danielhams**
- querying the current frame time both in/out of the jack process() call
- set the xrun callback method and have it called as expected
- unregister a jack port
- query the latency range on a port

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
Hi Daniel,

Thanks for the contributions.  It's going to be a week or two until I can look at this properly.  Generally looks good, but I have a couple of questions / comments -
- There doesn't seem to be a method to make use of the latency query (have I missed something)??  Would assume it should be in JackPort?
- JackLatencyRange should wrap, not extend, the JNA structure (as per JackMidi.Event).  The general principle is that nothing outside of the lowlevel package should have a public reference to anything in JNA.  One day there might be a desire to provide an alternative native backing, not that the name JNAJack is great for that! ;-)
- The switch to long isn't correct for mapping uint32 (does the JackLatencyRange structure even work??).  See https://github.com/twall/jna/blob/master/www/Mappings.md  Returning long from the public facing API might be the correct approach, though.  I think the conversion would be nativeResult & 0xFFFFFFFFL ??
- I hadn't thought about removing the process callback using null.  Is there any documentation on when this can be done?  What's your use?  The added call into jackLib.jack_set_process_callback needs wrapping in catch(Throwable ..) too - this is to catch JNA errors.

Thanks and best wishes, Neil

**Comment by danielhams** [comment]
Hi Neil,

Good questions. Don't burn any further time reviewing this as it is - I'll rework it a bit to take into account your comments and come up with some detail about places where there's some ambiguity.

Basically I had these little changes against an old version of jnajack - when I rolled forward to your current HEAD some bits are MIA (LatencyRange accessors). Other bits are indeed questionable :-)

Some quick answers to you questions:

(1) Latency accessors - yep, I forget to add the methods to the HEAD version of port

(2) Wrapping instead of extending jack_latency_range_t - no probs. I'll update to reflect the approach of MidiEvent.

(3) Use of long vs int for jack_nframes_t - fair point - I'll roll it back to "int" - but will point out that jack_types.h defines JACK_MAX_FRAMES to be a big number (4294967295U) that doesn't fit in java signed int. As you mention, perhaps making the public API use long but JNA implementation use int is "best effort".

(4) Setting callbacks to null - I'll fix the missing catch sections. The reason I added these was jack internally sets up bitset style maps of which callbacks a particular client uses (see https://github.com/jackaudio/jack1/blob/master/libjack/client.c#L2784 in jack1) and it's fine to pass NULL to invalidate that setting.

I use it when my application preferences change to a different audio backend (e.g. coreaudio) and I wish to unregister/clean up appropriately. I vaguely remember having issues with dangling threads being visible inside my profiler too, but that's possibly something else - this change was part of that investigation that was (I think) a sensible change for regular use.

(5) Something else I missed was removing the port from the internal ports list when unregisterPort is called (given that registerPort calls addToPortArray). I'll look into this, too.

I'll try and rollback/patch forward this branch so that it's vaguely clear what the differences are.

Cheers, Dan

**Comment by neilcsmith-net** [comment]
Generally sounds good.

You've missed my point about int vs long though.  The important thing for JNA is the size of the type 32bit or 64bit, which can cause various problems if it's wrong (eg. incorrect struct size calculation).  If a native function returns an unsigned int, the bits returned by JNA will (should!) still be correct, hence my suggested conversion above (same as Integer.toUnsignedLong(), except that's Java 8 and I don't want to stop supporting 7 yet)

Integer.MAX_VALUE & 0xFFFFFFFFL = 2147483647
(Integer.MAX_VALUE + 1) & 0xFFFFFFFFL = 2147483648
-1 & 0xFFFFFFFFL = 4294967295

It's not "best effort", it's correct! ;-)

Best wishes, Neil

**Comment by danielhams** [comment]
Right you are. I've got the zen I think now.

I added a couple of static methods on a util class to convert to and from "native int" to Java long.

The style question comes in whether you'd wish for this "long" version of int to be returned everywhere in the API in place of jack_nframes_t?

For the moment in the code I've only used it in places where it would make sense that a very large value could be returned in everyday use of jack - so only:

JackClient.getLastFrameTime()
JackClient.getFrameTime()

As an aside, I don't know what you'd like to do with test classes, so here's the "main" testing method for that native to long converter:

```
public static void main( String args[] )
{
    int[] intValsToTest = {
            -2,
            -1,
            0,
            1,
            2,
            Integer.MIN_VALUE,
            Integer.MIN_VALUE+1,
            Integer.MIN_VALUE/2,
            Integer.MAX_VALUE,
            Integer.MAX_VALUE-1,
            Integer.MAX_VALUE/2
    };

    long[] longValsToTest = new long[ intValsToTest.length ];
    for( int i = 0 ; i < intValsToTest.length ; ++i )
    {
        longValsToTest[i] = intValsToTest[i];
    }
    // Replace first two longs with big values
    longValsToTest[0] = 4294967294L;
    longValsToTest[1] = 4294967295L;

    System.out.println("Beginning integer roundtrip checks");

    for( int val : intValsToTest )
    {
        // -1 should give jack's MAX_FRAMES
        int javaVal = val;
        long largeValAsLong = nuint32ToJlong(javaVal);
        int largeLongBack = jlongToNuint32(largeValAsLong);
        System.out.println( "JV(" + javaVal + ") -> AL(" + largeValAsLong + ") -> JV(" + largeLongBack + ")");
        if( javaVal != largeLongBack )
        {
            System.out.println("Failed back and forth test for source int: " + val);
        }
    }

    System.out.println("Beginning long integer roundtrip checks");

    for( long val : longValsToTest )
    {
        // We know that negative long values won't roundtrip, skip them
        if( val < 0 ) continue;
        int valAsInt = jlongToNuint32(val);
        long andBack = nuint32ToJlong(valAsInt);
        System.out.println( "JLV(" + val + ") -> NU(" + valAsInt + ") -> LV(" + andBack + ")");
        if( val != andBack )
        {
            System.out.println("Failed back and forth test for source long: " + val);
        }
    }
}
```

I also gave it the once over by altering Jack itself so that get_latency_range returned JACK_MAX_FRAMES and all is well.

D

**Comment by danielhams** [comment]
One final aside, do you have somewhere you discuss the code itself other than github? I'd like to pose some questions about performance, latency and JNA vs JNI and github issues aren't really the forum for that.

**Comment by neilcsmith-net** [comment]
> One final aside, do you have somewhere you discuss the code itself other than github?

Try https://groups.google.com/d/forum/jaudiolibs  It's not very active, so feel free to come on over and liven things up! ;-)

**Comment by neilcsmith-net** [comment]
Following up from mailing list discussion - apologies I'd completely missed the extra commits amongst the dialogue and realise AFAICT you've addressed the points raised earlier.

One further thing and then I'll pull this in - please can you move NativeToJavaTypeConverter into the main package and make it package private.  That way it's not public API, and the examples and util packages are destined for removal anyway (everything in them is deprecated).

Also, maybe TypeConverters?  I thought I was too verbose! ;-P

**Comment by danielhams** [comment]
No probs. I've moved it into the main package and made the class default visible.

(Too verbose :-) ItSeemsYouDon'tLikeDescriptiveIdentifiers.doIt();

It's a habit I picked up working with non-native english speakers - the more info you give them to go on, the less they come and bug you.

**Comment by neilcsmith-net** [comment]
OK, merged to master.  Will do some testing and see about an up-to-date release ASAP (not this week though!)

> (Too verbose :-) ItSeemsYouDon'tLikeDescriptiveIdentifiers.doIt();

Not true! I thought I _was_ being descriptive until I saw your code. ;-p

Thanks for the contribution, Neil

**Pull request merged**
