### PR TITLE
Add isRealtime() method to JackClient

### PR DESCRIPTION
**Pull request by markjfisher**
As a software dev myself, I couldn't do this change without a test 😄 

I've add a test class for JackClient, and introduced Mockito and JUnit5.

I also made the Jack class an interface for easier mocking without side effects, but there's a couple of methods used at package level that became public as a consequence of this; setupCTI, forceThreadDetach, which is a little unclean. Also, I didn't add javadoc for those interface methods yet.
I wanted to get some feedback first.

### CODE REVIEW

**Comment by markjfisher** [comment]
This is to address #16

**Comment by neilcsmith-net** [comment]
Please limit the changes to the addition of the required method.  Please don't reformat whitespace in the same PR.  And please don't change the source / binary compatibility in the PR, particularly just for tests.

Tests with Jack would be more useful than tests without, although requiring Jack to build might be annoying.

If you do want to add tests with mocking, I'd suggest you're mocking the wrong thing.  Mock the lowlevel library binding, and open up a package visible constructor on Jack?

**Comment by markjfisher** [comment]
I didn't realise it was whitespace reformatting, IntelliJ must have done that without my knowledge.
I also didn't realise converting Jack to an interface would be a binary issue.
I'll revert it to just the change, it was an interesting adventure into adding tests, but I think I was biting off more than I should have.

**Comment by markjfisher** [comment]
For reference, I'm trying to rewrite falkTX's Catia interface, specifically working through this code:
https://github.com/falkTX/Catia/blob/78b0307afeded440c80a2b1d732dd15382f7b335/src/catia.py

I've noticed some other functions not implemented, but they aren't getting in the way (e.g. jack_port_by_name, but I can use the regex and enums to achieve the same effect in `getPorts`).

However, I've hit a function that is commented out in the code base, and I was wondering if it can be implemented?

```java
//    public native int jack_port_get_aliases(_jack_port port, ByteBuffer[] aliases);
```
In Catia, it's used to display the ports with nice names (the code is here: https://github.com/falkTX/Catia/blob/78b0307afeded440c80a2b1d732dd15382f7b335/src/catia.py#L538):

image

Do you think it would be something that could be enabled in jnajack?

**Comment by neilcsmith-net** [comment]
Nice!  I [do like graph UIs!](https://www.praxislive.org) :smile:  Somewhat OT, but what graphics toolkit will you use?

I haven't updated this project for a few years now, although I still use it - haven't needed to.  Anything commented out or not available is usually due to functions that couldn't be linked on all versions of Jack in support at the time (which needs some care) or problematic method signatures generated by JNAerator that I hadn't got around to fixing.

Anything in Jack is fair game to add.  Let's keep conversations separate.  I'll check and aim to merge this one next week.

**Comment by markjfisher** [comment]
OT continuation: I've used lwjgl before for doing [visualisations of aoc puzzles](https://github.com/markjfisher/advent-of-code/blob/master/visualisations/src/main/kotlin/engine/Window.kt), with an opengl engine. I created a 3d engine for interacting with the scene, and [doing camera movement along parametric curves](https://www.youtube.com/watch?v=-oHCplaBswU) in real time. Hadn't done any 3d before, so it was a bit of a learning curve.
For the menu part of the app, I used imgui as the DSL was pretty easy to use.

For this, I may just use [imgui](https://github.com/kotlin-graphics/imgui), but suggestions welcome!

**Comment by neilcsmith-net** [comment]
Thanks for the addition.  Merged.

I've had a look at integrating testing using Mockito too - not merged to master yet - see #18 Input welcomed.

OT : interesting stuff.  Using LWJGL myself, and have considered imgui.  Hadn't seen it seems to have a node UI already?  Aside from the obvious (JavaFX or Swing, which PraxisLIVE using for the IDE as it's NetBeans based), I find [Skija](https://github.com/HumbleUI/Skija/) interesting.  I just hate Kotlin!  As you don't, [OpenRNDR](https://openrndr.org/) might also be of interest.  If you want to follow up on the OT, or other aspects of JNAJack, my email is on my GitHub profile.

**Pull request merged**
