### PR TITLE
fixed compile errors with Maven 3.0.5

### PR DESCRIPTION
**Pull request by smay4finger**
Maven 3.0.5 uses the maven-compiler-plugin 2.0.2 with version 1.3 as the default source setting. As the source is using 1.5 features, the compile fails. With maven-compiler-plugin 2.3 the default source setting changed to 1.5.

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
Thanks for the contribution.  My Maven-fu is distinctly lacking!  However, I'm not sure this is quite correct.  I think we should be explicitly specifying source and target versions, and they should be 1.6 rather than 1.5 anyway.

**Comment by smay4finger** [comment]
Hope this is better, I'm not a Maven expert. Maybe it would be better to use the newest available maven-compiler-plugin? At least it's better than not telling explicitly telling which JRE version to use.

**Comment by smay4finger** [comment]
A friendly reminder, as this pull request is open for a while now.

**Comment by neilcsmith-net** [comment]
@smay4finger yes, sorry about that!  This project hasn't been top of my list recently, but there are a few things I want to look at, including the Maven config.  I'll aim to look into this when I'm back from holidays towards the end of the month.

**Comment by neilcsmith-net** [comment]
Closing this as it's been superseded and JNAJack is now in central. Thanks!

**Pull request closed without merging**
