### PR TITLE
Added Nullability annotations and minor documentation fixes

### PR DESCRIPTION
**Pull request by basshelal**
This Pull Request changes no executable code or implementation, it only makes the front facing API a little more friendly and usable.

## Nullability Annotations

I have added Nullability annotations to any public API methods. 

They are added to parameters or return types to tell IDEs and users whether a type is expected to be allowed to be `null` or not.

IDEs such as IntelliJ use these annotations to detect possible `NullPointerException`s and the Kotlin programming language uses these to determine the nullability of a type (ie whether it is `String?` or `String`, if it doesn't know the nullability, which is the usual case with external Java libraries, it always defaults to `String!` which is basically useless). But Java users also benefit as well since IntelliJ does this with Java too.

You can read more about these annotations [here](https://www.jetbrains.com/help/idea/nullable-and-notnull-annotations.html).

For determining nullability I had to read through the code and see where a parameter is going and how it is being used, if a parameter is going directly and only into a native implementation/method I have assumed it is `@NotNull` for safety. If I recall correctly, all return types are `@NotNull` since the library is Exception happy and throws `Exception`s rather than returning `null`s.

 By adding these annotations, I have added one dependency to `pom.xml` but it is a small one consisting only of annotations.

## Javadoc Tags

I also fixed a few Javadoc tags (mostly incorrect `JackException` links) and added `@deprecated` tags leading users to the new API to use.

The documentation can definitely be better, but that's a job for another time.

## NullPointerException Messages

I have added messages to some of the `NullPointerException`s pointing the user to what was passed as `null` incorrectly, these are mostly to do with registering callbacks in `JackClient.java`. I have tried to keep the language and format similar to what already exists.

## README

I have updated the README to be a little more approachable and usable to new users.

Specifically I have shown users how to install the library and a quick start to using it so they can know where to go and how to get familiar with the library, it is quite minimal  though so I do reference the example repository.

It definitely could use a bit more work, but I feel like this is good enough for the time being.

## Thanks

Thanks for this awesome library, it really is a lifesaver, and thanks for your other stuff as well, I'd really like to get into Audio Development on the JVM using Kotlin and your work has been a huge help to me!

### CODE REVIEW

**Comment by neilcsmith-net** [comment]
Thanks for the PR, and thanks for the thanks! :smile:

This library hasn't seen much change in the last few years.  The docs changes and readme addition really would be good to get in.  The annotations I am more sceptical about, although the null safety in the type system is possibly the one thing I prefer about Kotlin!

- Can we make the annotations optional at runtime?  eg. does `provided` work, on module and class path? I don't really want another required dependency.
- Do other IDE's work OK with JetBrains' take on JSR305?  Will check NetBeans (that's essential here, but guess should check Eclipse supports this too).  What about Kotlin side?
- Is there any way to set `@NotNull` as a package / class default so we only need `@Nullable` on parameters, etc.?

Possibly now is the time to pull out the deprecated stuff and move to 2.0 anyway.

**Comment by basshelal** [comment]
Thanks for the feedback and the prompt response! 😊

Lots of things I myself was actually thinking about regarding the annotations and all very valid and important!

I'll see what I can do regarding this and get back to you, because I fully agree with you and from what I've briefly read online, it seems what you propose is possible and has been done elsewhere, I just need to fiddle with it and test it properly.

I think a 2.0 release would benefit from updated and more detailed documentation, something I'd be willing to do (but on a different PR dedicated to just that).

I'll keep looking around and testing stuff regarding the annotations and I'll get back to you.

Cheers! 😊

**Comment by basshelal** [comment]
Hi @neilcsmith-net 

I've made the nullability checks more concise by using [com.google.code.findbugs.jsr305](https://mvnrepository.com/artifact/com.google.code.findbugs/jsr305/3.0.2) which allows us to make a default nullability, specifically I've made it so that method parameters and return types are `@NonNull` by default unless marked as `@Nullable` which is much fewer, making the code much cleaner and concise.

Doing so meant I added a `package-info.java` for the main package. The new dependency replaces the JetBrains annotations and it seems to work when using the `provided` scope but I'm quite clueless when it comes to my preferred build system (Gradle) let alone Maven so I really am not sure about much of this stuff.

I have however, checked Java and Kotlin nullability checks from a user's point of view and they seem to work, the IDE gives warnings and hints whenever I try to contradict the expectation (passing `null` to a `@NonNull` parameter or doing a `null` check on a `@NonNull` return) and type inference from Kotlin is always correct.

Let me know what you think about this, I hope it is good.

Cheers 😊

**Comment by neilcsmith-net** [comment]
No-one's preferred build system should be Gradle, but then again neither should their preferred IDE be IntelliJ :wink: 

This would be a good step forward.  Did you check that projects work without the annotation jar available?

Now, the downside - I also have concerns about that source of annotations - it's old, in the `javax` namespace, and doesn't have an automatic module name.  Although I'm not sure if there's any need for it at runtime anyway?  But optionality and compatibility with JPMS are hard requirements, so that needs checking.

And of course, usable for Kotlin :smile: so I guess this is a useful link - https://github.com/JetBrains/kotlin/blob/master/core/compiler.common.jvm/src/org/jetbrains/kotlin/load/java/JvmAnnotationNames.kt

Googling for replacements for JSR305 does open a minefield of (sometimes contradictory) information!

Thanks!

**Comment by basshelal** [comment]
> Did you check that projects work without the annotation jar available?

No but how could I go about doing that? Create a new project/module in the project directory that depends on the library but doesn't have the annotations installed (ie listed in the dependencies)?

With regards to the modules I honestly have no idea about any of that or where to look, can you help me out with this or at least guide me in the right direction.

Apologies for my lack of knowledge in this realm, I've never used a lot of this stuff before (Maven, Java Modules etc) so I'm a little less informed than I could be.

Thanks

**Comment by neilcsmith-net** [comment]
> Create a new project/module in the project directory that depends on the library but doesn't have the annotations installed (ie listed in the dependencies)?

Basically, yes.  I guess maybe increase the version number of the library in the pom (to make sure you're picking up your changes), build and mvn install it, then increase the version for the dependency in your own project or the examples.  Need to make sure that a) it doesn't pull in the annotation dependency in the build, and b) it all works without the annotation jar!

No problem on the lack of Maven / JPMS knowledge.  And thanks for looking into this.  Your knowledge of Kotlin is going to be more than mine anyway!  Unfortunately I don't have the right direction to look at for this myself right now, and going to be tied up with some work on another library (GStreamer) for a few weeks at least.  I won't forget the PR, but might be early next year before I can follow up on this issue further.

Thanks!

**Comment by basshelal** [comment]
Hi @neilcsmith-net 
Been a while I know but I finally got back to this and I think I got everything working properly as you detailed, I'll explain what I did.

* Bump version in `pom.xml` to 1.5.0
* Run `mvn install`, this will create a jar library in my maven local repository located in `~/.m2/repository` and in `./target`
* Create a new project (I used Gradle but it doesn't matter, Maven can also obviously work)
* Add `mavenLocal` to the repositories that Gradle can use, I found this to work better than just using the lone jar
* Add the new version dependency that is: `org.jaudiolibs:jnajack:1.5.0`, this will be pulled from `mavenLocal`
* Now we can code
* I just copied the code from `SimpleAudioClient.java` and added a `main` function to run it
* Everything should compile and run and should interact correctly with JACK
* The nullability checks work, I tried to do `Jack.getInstance().openClient(null,null,null)` and the IDE warned me `Passing 'null' argument to parameter annotated as @NotNull` for the first argument which is indeed correct behavior
* I tried to import or use `@NotNull` or `@Nullable` in the new project but they were not recognized so clearly not pulled despite the IDE recognizing nullability so clearly the dependency was not pulled but the annotations were kept at runtime, in fact the IDE reports the only dependencies pulled were `org.jaudiolibs:jnajack:1.5.0` and `net.java.dev.jna:jna:5.7.0`

I removed the incorrect `public` from `@AllMethodsAreNonnullByDefault` because it was actually incorrectly visible to my new project, having it package private still works.

You can change the version in `pom.xml` to whatever, I just used something that will be higher than the current.

I think that's everything with regards to Nullability annotations, I might want to do some quality of life documentation improvements in another pull request at some point in the future.

Hopefully you can accept these changes and find them useful and hopefully this isn't the last pull request I make to this repository.

Many thanks 😊

**Comment by neilcsmith-net** [comment]
Thanks @basshelal Sorry, still not had much time to follow up on this.  I've changed the base branch here so I can pull in and check.  My main concerns are still ensuring we don't bring in extra dependencies, it works across as many tools as possible, and it's JPMS compatible.

For more on JPMS issues see things like https://nipafx.dev/jsr-305-java-9/  Or take a look at this massive thread https://github.com/google/guava/issues/2960 - lots of projects seem to be looking at moving off of jsr305, but no clear idea of what the best and most compatible option is to choose here. :confused: 

Yes, despite calling the branch jsr305, I think the answer has to _not_ be jsr305. :smile:

**Comment by basshelal** [comment]
No worries, I completely understand, this is a weird issue (that makes the Java ecosystem look bad 😕) and I understand and respect your reluctance to merge.

In any case the basic framework is there, whether it's using the annotations I provided or someone else's, the hard part is mostly done and worst case scenario; if you decide to refuse these annotations entirely, we could always just remove them and write better docs to explain whether a parameter expects `null` or not, it's not ideal but I don't want things to break just for what is generally seen as a luxury and not a necessity. I want to help but not if it's going to cause problems or breakages that aren't worth it.

Anyway let me know what I can do in this regard, I am happy to help and contribute in any way.

Many thanks again 😊

**Pull request closed without merging**
